#!/bin/bash

# Install general tools
sudo apt install -y vim tmux ranger zsh wget curl cmake fonts-powerline silversearcher-ag

# Switch to zsh and ohmyzsh
chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp themes/zsh/ken.zsh-theme $HOME/.oh-my-zsh/themes/

# Copy config files
for file in $(ls configs); do
    cp configs/$file $HOME/.$file
done

# Copy utility scripts into the path
mkdir -p $HOME/bin
cp -r scripts/* $HOME/bin

# Get Vim set up
if [ ! -d "$HOME/.vim/colors" ]; then
    mkdir -p $HOME/.vim/colors
fi
cp -r themes/vim/colors/* $HOME/.vim/colors/
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Set up tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm¬
